title:              Alexander Lacson
email:              lacsonalexanderz@gmail.com
description:        Data Scientist
author:             Alexander Lacson
baseurl:            ""
url:                "https://max-torch.github.io"

# Social Profiles
twitter_username:   
github_username:    max-torch
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
kramdown:
    math_engine:    katex
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
highlighter: rouge